### ISSUE TITLE
Chrome does not work with your cdn

### ISSUE THREAD

**Issue by dimmduh** [codex-team/hawk.javascript#20]
Error on console

Refused to execute script from 'https://cdn.rawgit.com/codex-team/hawk.javascript/master/hawk.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.

**Comment by talyguryn** [comment]
Hey, @dimmduh 

Also you get a 404 error for this response. It is not a Chrome's bug.

![](https://capella.pics/c456eb7a-1f58-425d-b6d8-a0033e5fa7c2.jpg)

We have moved package's main file from `/hawk.js` to `/dist/hawk.js` location.

## How to use RawGit CDN

RawGit can return files by target repo's branch of specific commit hash.
`https://cdn.rawgit.com/`**owner**`/`**repo**`/`**branch_or_commit**`/`**path_to_file**

 In this link you passed `master` as a branch name.

`https://cdn.rawgit.com/codex-team/hawk.javascript/master/hawk.js`

So on repo (branch) updates some files could be moved (why not) and you'll get 404 on their last locations.

That's why you should use links with a commit's hash on production.

![](https://capella.pics/dce17701-dda1-496e-83d9-bf64bac87e43.jpg/cover/eff2f5)

Read «[Load from CDN](https://github.com/codex-team/hawk.javascript/tree/c82ef451cd16140f933c73b6301e7b421159ffb7#load-from-cdn)» part of installation guide.

## Getting NPM-package sources from CDN

We have found a better way to load single-file NPM package script from [jsDelivr CDN](https://www.jsdelivr.com).

![](https://capella.pics/8069cfe2-e05e-4494-8a1d-88565a76b10a.jpg/cover/eff2f5)

You can load a target version main script of package.

`https://cdn.jsdelivr.net/npm/`**package**`@`**version**

To get the latest `hawk.javascript` use the following link. You need no enter path to target file.

`https://cdn.jsdelivr.net/npm/hawk.javascript@2.0.0`
