### ISSUE TITLE
React integration: parse maps and show sources in garage

### ISSUE THREAD

**Issue by talyguryn** [codex-team/hawk.javascript#74]
check can we use [hawk.webpack.plugin](https://github.com/codex-team/hawk.webpack.plugin) to send sourcemaps for:

- [x] custom react build
- [x] cra
- [x] rewired cra

**Comment by ilyamore88** [comment]
## `yarn eject` in create-react-app
I used instructions from the plugin repo: https://github.com/codex-team/hawk.webpack.plugin#install.
Then I added the plugin to `config/webpack.config.js`.

### Troubleshooting
I had an error with getting information about chunks. I resolved this issue by adding to config this:
```
futureEmitAssets: false
```
This issue is actual only for Webpack 4, in Webpack 5 this variable is `false` by default.

**Comment by ilyamore88** [comment]
Error:
```
The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
```

**Comment by ilyamore88** [comment]
Fix:
```js
config.output.futureEmitAssets = false;
```

**Comment by ilyamore88** [comment]
## create-react-app with rewired
I installed [react-app-rewired](https://github.com/timarney/react-app-rewired).
Then I overrode my webpack config. This is my `config-overrides.js`:
```js
const HawkWebpackPlugin = require("@hawk.so/webpack-plugin");

module.exports = function override(config, env) {
    config.plugins = [
        ...config.plugins,
        new HawkWebpackPlugin({
            integrationToken: 'token' // Your project's Integration Token
        })
    ];
    config.devtool = 'hidden-source-map';
    config.output.futureEmitAssets = false;

    return config;
}
```

**Comment by ilyamore88** [comment]
## Custom React build
With Webpack 4 is all okay, with Webpack 5 I had a problem https://github.com/codex-team/hawk.webpack.plugin/issues/23.

**Comment by ilyamore88** [comment]
Done 🎆
